language: php

php:
  - 5.4

before_script:
  - wget https://commondatastorage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.2.zip
  - unzip google_appengine_1.9.2.zip > /dev/null
  - cd google_appengine_1.9.2
  - python dev_appserver.py --help
  - python dev_appserver.py --port=9080 ../
  - cd ..
  - composer install

script: bin/behat

