language: php

php:
  - 5.4

before_script:
  - wget https://commondatastorage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.2.zip
  - unzip google_appengine_1.9.2.zip > /dev/null 
  - composer install
  - ls -l
script: bin/behat

