language: php

php:
  - 5.4

before_script:
  - phpinfo()
#  - wget https://commondatastorage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.2.zip
#  - unzip google_appengine_1.9.2.zip > /dev/null
#  - ls -l
#  - cd google_appengine
#  - python dev_appserver.py --help
#  - python dev_appserver.py --port=9080 --php_executable_path== --skip_sdk_update_check=True ../ &
#  - cd ..
#  - composer install

script: bin/behat

